CREATE TABLE "ECAPTURE_ACTION"  ( 
	"ACTION_ID"      	NUMBER(15,5) NOT NULL,
	"ACTION_ALIAS"   	VARCHAR(50) NULL,
	"ACTION_NAME"    	VARCHAR(50) NOT NULL,
	"ACTION_NAME_AR" 	VARCHAR(50) NULL,
	"ACTION_DESC"    	VARCHAR(150) NULL,
	"ACTION_GROUP_ID"	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_ACTION" PRIMARY KEY("ACTION_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_ACTION_GROUP"  ( 
	"ACTION_GROUP_ID"     	NUMBER(15,5) NOT NULL,
	"ACTION_GROUP_NAME"   	VARCHAR(50) NOT NULL,
	"ACTION_GROUP_NAME_AR"	VARCHAR(50) NULL,
	"ACTION_GROUP_DESC"   	VARCHAR(150) NULL,
	CONSTRAINT "PK_ECAPTURE_ACTION_GROUP" PRIMARY KEY("ACTION_GROUP_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_BATCH"  ( 
	"BATCH_ID"             	NUMBER(15,5) NOT NULL,
	"BATCH_ALIAS"          	VARCHAR(50) NULL,
	"BATCH_NAME"           	VARCHAR(50) NOT NULL,
	"BATCH_NAME_AR"        	VARCHAR(50) NULL,
	"BATCH_CREATE_DATETIME"	TIMESTAMP(5) DEFAULT SYSDATE NOT NULL,
	"BATCH_UPDATE_DATETIME"	TIMESTAMP(5) NULL,
	"BATCH_PERIOD"         	VARCHAR(25) NULL,
	"BATCH_CREATED_BY"     	NUMBER(15,5) NOT NULL,
	"BATCH_STATUS"         	CHAR(1) DEFAULT 0 NULL,
	"DATACLASS_ID"         	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_BATCH" PRIMARY KEY("BATCH_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_DATACLASS"  ( 
	"DATACLASS_ID"             	NUMBER(15,5) NOT NULL,
	"DATACLASS_NAME"           	VARCHAR(25) NOT NULL,
	"DATACLASS_NAME_AR"        	VARCHAR(25) NULL,
	"DATACLASS_USEDFOR"        	CHAR(1) NOT NULL,
	"DATACLASS_STATUS"         	CHAR(1) DEFAULT 1 NULL,
	"DATACLASS_INDEX"          	NUMBER(15,5) NULL,
	"DATACLASS_DESC"           	VARCHAR(25) NULL,
	"DATACLASS_FIELD_COUNT"    	NUMBER(15,5) DEFAULT 0 NOT NULL,
	"DATACLASS_CREATE_DATETIME"	TIMESTAMP(5) NOT NULL,
	"DATACLASS_UPDATE_DATETIME"	TIMESTAMP(5) NULL,
	"DATACLASS_CREATED_BY"     	NUMBER(15,5) NOT NULL,
	"DATACLASS_ISREAL"         	CHAR(1) DEFAULT 0 NULL,
	"DATACLASS_CLONED_INDEX"   	NUMBER(15,5) NULL,
	CONSTRAINT "PK_ECAPTURE_DATACLASS" PRIMARY KEY("DATACLASS_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_DOCUMENT"  ( 
	"DOCUMENT_ID"             	NUMBER(15,5) NOT NULL,
	"DOCUMENT_ALIAS"          	VARCHAR(50) NULL,
	"DOCUMENT_NAME"           	VARCHAR(50) NOT NULL,
	"DOCUMENT_NAME_AR"        	VARCHAR(50) NULL,
	"DOCUMENT_PAGES"          	NUMBER(15,5) NULL,
	"DOCUMENT_EXTENSION"      	VARCHAR(25) NOT NULL,
	"DOCUMENT_STATUS"         	CHAR(1) NULL,
	"DOCUMENT_ISAUTONAMING"   	CHAR(25) NULL,
	"DOCUMENT_ORDER"          	NUMBER(15,5) NULL,
	"DOCUMENT_CREATE_DATETIME"	TIMESTAMP(5) NOT NULL,
	"DOCUMENT_UPDATE_DATETIME"	TIMESTAMP(5) NULL,
	"DOCUMENT_CREATED_BY"     	NUMBER(15,5) NOT NULL,
	"BATCH_ID"                	NUMBER(15,5) NOT NULL,
	"FOLDER_ID"               	NUMBER(15,5) NULL,
	CONSTRAINT "PK_ECAPTURE_DOCUMENT" PRIMARY KEY("DOCUMENT_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_DOCUMENT_FIELD"  ( 
	"SOURCE_ID"       	NUMBER(15,5) NOT NULL,
	"DATACLASS_ID"    	NUMBER(15,5) NOT NULL,
	"DATACLASS_FIELD1"	VARCHAR(150) NULL,
	"DATACLASS_FIELD2"	VARCHAR(150) NULL,
	"DATACLASS_FIELD3"	VARCHAR(150) NULL,
	"DATACLASS_FIELD4"	VARCHAR(150) NULL,
	"DATACLASS_FIELD5"	VARCHAR(150) NULL,
	"DATACLASS_FIELD6"	VARCHAR(150) NULL,
	"DATACLASS_FIELD7"	VARCHAR(150) NULL,
	CONSTRAINT "PK_ECAPTURE_DOCUMENT_FIELD" PRIMARY KEY("SOURCE_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_FIELD"  ( 
	"FIELD_ID"           	NUMBER(15,5) NOT NULL,
	"FIELD_ALIAS"        	VARCHAR(50) NULL,
	"FIELD_NAME"         	VARCHAR(50) NOT NULL,
	"FIELD_NAME_AR"      	VARCHAR(50) NULL,
	"FIELD_TYPE"         	CHAR(25) NULL,
	"FIELD_INDEX"        	NUMBER(15,5) NULL,
	"FIELD_SIZE"         	NUMBER(15,5) DEFAULT 0 NULL,
	"FIELD_STATUS"       	CHAR(1) DEFAULT 1 NULL,
	"FIELD_MANDATORY"    	CHAR(25) DEFAULT 0 NULL,
	"FIELD_TEXTLINES"    	NUMBER(15,5) DEFAULT 0 NULL,
	"FIELD_LOOKUP_ID"    	NUMBER(15,5) NULL,
	"FIELD_TOOLTIP"      	VARCHAR(50) NULL,
	"FIELD_TOOLTIP_AR"   	VARCHAR(50) NULL,
	"FIELD_DEFAULT_VALUE"	VARCHAR(25) NULL,
	"FIELD_ORDER"        	NUMBER(15,5) NOT NULL,
	"DATACLASS_ID"       	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_FIELD" PRIMARY KEY("FIELD_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_FOLDER"  ( 
	"FOLDER_ID"             	NUMBER(15,5) NOT NULL,
	"FOLDER_ALIAS"          	VARCHAR(50) NULL,
	"FOLDER_NAME"           	VARCHAR(50) NOT NULL,
	"FOLDER_NAME_AR"        	VARCHAR(50) NULL,
	"FOLDER_INDEX"          	VARCHAR(25) NULL,
	"FOLDER_PARENTINDEX"    	VARCHAR(25) NULL,
	"FOLDER_CREATE_DATETIME"	TIMESTAMP(5) NOT NULL,
	"FOLDER_UPDATE_DATETIME"	TIMESTAMP(5) NULL,
	"DATACLASS_ID"          	NUMBER(15,5) NOT NULL,
	"FOLDER_CREATED_BY"     	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_FOLDER" PRIMARY KEY("FOLDER_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_GROUP"  ( 
	"GROUP_ID"       	NUMBER(15,5) NOT NULL,
	"GROUP_NAME"     	VARCHAR(50) NOT NULL,
	"GROUP_NAME_AR"  	VARCHAR(50) NULL,
	"GROUP_DESC"     	VARCHAR(150) NULL,
	"GROUP_PARENT_ID"	NUMBER(15,5) NULL,
	CONSTRAINT "PK_ECAPTURE_GROUP" PRIMARY KEY("GROUP_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_GROUP_AUTHORITY"  ( 
	"GROUP_ID"	NUMBER(15,5) NOT NULL,
	"AUTHORITY_ID" 	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_GROUP_AUTHORITY" PRIMARY KEY("GROUP_ID","AUTHORITY_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_GROUP_USER"  ( 
	"GROUP_ID"	NUMBER(15,5) NOT NULL,
	"USER_ID" 	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_GROUP_USER" PRIMARY KEY("GROUP_ID","USER_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_LOG"  ( 
	"LOG_ID"      	NUMBER(15,5) NOT NULL,
	"LOG_ALIAS"   	VARCHAR(50) NULL,
	"LOG_DATETIME"	TIMESTAMP(5) DEFAULT SYSDATE NOT NULL,
	"USER_ID"     	NUMBER(15,5) NOT NULL,
	"ACTION_ID"   	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_LOG" PRIMARY KEY("LOG_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_LOG_COMPONENT"  ( 
	"LOG_COMPONENT_ID"	NUMBER(15,5) NOT NULL,
	"LOG_ID"    	NUMBER(15,5) NOT NULL,
	"TABLE_NAME"	VARCHAR(25) NOT NULL,
	"RECORD_ID" 	NUMBER(15,5) NOT NULL,
	"FIELD_NAME"	VARCHAR(25) NOT NULL,
	"OLD_VALUE" 	VARCHAR(50) NOT NULL,
	"NEW_VALUE" 	VARCHAR(50) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_LOG_COMPONENT" PRIMARY KEY("LOG_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_LOG_MAIL"  ( 
	"LOG_MAIL_ID"          	NUMBER(15,5) NOT NULL,
	"LOG_MAIL_SENDER"      	NUMBER(15,5) NOT NULL,
	"LOG_MAIL_TO"          	VARCHAR(25) NOT NULL,
	"LOG_MAIL_CC"          	VARCHAR(25) NULL,
	"LOG_MAIL_SUBJECT"     	VARCHAR(25) NOT NULL,
	"LOG_MAIL_BODY"        	VARCHAR(25) NULL,
	"LOG_MAIL_ATTACH_COUNT"	VARCHAR(25) NULL,
	"LOG_MAIL_ATTACH_NAMES"	VARCHAR(25) NULL,
	"LOG_ID"               	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_LOG_MAIL" PRIMARY KEY("LOG_MAIL_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_LOOKUP"  ( 
	"LOOKUP_ID"       	NUMBER(15,5) NOT NULL,
	"LOOKUP_PARENT_ID"	NUMBER(15,5) NULL,
	"LOOKUP_NAME"     	VARCHAR(50) NOT NULL,
	"LOOKUP_NAME_AR"  	VARCHAR(50) NULL,
	"LOOKUP_DESC"     	VARCHAR(150) NULL,
	"LOOKUP_DESC_AR"  	VARCHAR(150) NULL,
	"LOOKUP_ORDER"    	NUMBER(15,5) NULL,
	"LOOKUP_DEFAULT"  	VARCHAR(25) NULL,
	"LOOKUP_STATUS"   	CHAR(1) DEFAULT 1 NULL,
	CONSTRAINT "PK_ECAPTURE_LOOKUP" PRIMARY KEY("LOOKUP_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_PERMISSION"  ( 
	"PERMISSION_ID"       	NUMBER(15,5) NOT NULL,
	"PERMISSION_TITLE"    	VARCHAR(50) NULL,
	"PERMISSION_STATUS"   	CHAR(1) DEFAULT 1 NULL,
	"PERMISSION_PARENT_ID"	NUMBER(15,5) NULL,
	CONSTRAINT "PK_ECAPTURE_PERMISSION" PRIMARY KEY("PERMISSION_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_AUTHORITY"  ( 
	"AUTHORITY_ID"    	NUMBER(15,5) NOT NULL,
	"AUTHORITY_TITLE" 	VARCHAR(50) NOT NULL,
	"AUTHORITY_STATUS"	CHAR(1) DEFAULT 1 NULL,
	CONSTRAINT "PK_ECAPTURE_AUTHORITY" PRIMARY KEY("AUTHORITY_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_AUTHORITY_PERMISSIONS"  ( 
	"AUTHORITY_ID"      	NUMBER(15,5) NOT NULL,
	"PERMISSION_ID"	NUMBER(15,5) NOT NULL 
	)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_USER"  ( 
	"USER_ID"                	NUMBER(15,5) NOT NULL,
	"USER_USERID"            	VARCHAR(25) NOT NULL,
	"USER_FNAME"             	VARCHAR(25) NULL,
	"USER_LNAME"             	VARCHAR(25) NULL,
	"USER_FNAME_AR"          	VARCHAR(25) NULL,
	"USER_LNAME_AR"          	VARCHAR(25) NULL,
	"USER_PASSWORD"          	VARCHAR(25) NOT NULL,
	"USER_STATUS"            	CHAR(1) DEFAULT 1 NULL,
	"USER_ISLOCKED"          	CHAR(1) DEFAULT 0 NULL,
	"USER_EXPIRY_DATE"       	TIMESTAMP(5) NULL,
	"USER_FAILED_LOGIN_COUNT"	NUMBER(15,5) DEFAULT 0 NULL,
	"USER_UNLOCK_DATETIME"   	TIMESTAMP(5) NULL,
	"USER_ISREAL"            	CHAR(1) DEFAULT 0 NULL,
	"USER_ACTING_AS"         	VARCHAR(25) NULL,
	"USER_EMAIL"             	VARCHAR(50) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_USER" PRIMARY KEY("USER_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
CREATE TABLE "ECAPTURE_USER_AUTHORITY"  ( 
	"USER_ID"	NUMBER(15,5) NOT NULL,
	"AUTHORITY_ID"	NUMBER(15,5) NOT NULL,
	CONSTRAINT "PK_ECAPTURE_USER_AUTHORITY" PRIMARY KEY("USER_ID","AUTHORITY_ID")
	NOT DEFERRABLE NOVALIDATE 
)
STORAGE( BUFFER_POOL DEFAULT )
PARALLEL( DEGREE DEFAULT )


/
ALTER TABLE "ECAPTURE_LOG"
	ADD ( CONSTRAINT "FK_ECAPTURE_ACTION"
	FOREIGN KEY("ACTION_ID")
	REFERENCES "ECAPTURE_ACTION"("ACTION_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_ACTION"
	ADD ( CONSTRAINT "FK_ECAPTURE_ACTION_GROUP"
	FOREIGN KEY("ACTION_GROUP_ID")
	REFERENCES "ECAPTURE_ACTION_GROUP"("ACTION_GROUP_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_DOCUMENT"
	ADD ( CONSTRAINT "FK_ECAPTURE_DOCUMENT"
	FOREIGN KEY("BATCH_ID")
	REFERENCES "ECAPTURE_BATCH"("BATCH_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_BATCH"
	ADD ( CONSTRAINT "FK_ECAPTURE_BATCH"
	FOREIGN KEY("DATACLASS_ID")
	REFERENCES "ECAPTURE_DATACLASS"("DATACLASS_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_DOCUMENT_FIELD"
	ADD ( CONSTRAINT "FK_ECAPTURE_DT_DOC_FIELD"
	FOREIGN KEY("DATACLASS_ID")
	REFERENCES "ECAPTURE_DATACLASS"("DATACLASS_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_FOLDER"
	ADD ( CONSTRAINT "FK_ECAPTURE_FOLDER"
	FOREIGN KEY("DATACLASS_ID")
	REFERENCES "ECAPTURE_DATACLASS"("DATACLASS_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_FIELD"
	ADD ( CONSTRAINT "FK_ECAPTURE_FIELD"
	FOREIGN KEY("DATACLASS_ID")
	REFERENCES "ECAPTURE_DATACLASS"("DATACLASS_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_DOCUMENT"
	ADD ( CONSTRAINT "FK_ECAPTURE_FOLDER_DOCUMENT"
	FOREIGN KEY("FOLDER_ID")
	REFERENCES "ECAPTURE_FOLDER"("FOLDER_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_GROUP_USER"
	ADD ( CONSTRAINT "FK_ECAPTURE_GROUP_USER_GROUP"
	FOREIGN KEY("GROUP_ID")
	REFERENCES "ECAPTURE_GROUP"("GROUP_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_GROUP_AUTHORITY"
	ADD ( CONSTRAINT "FK_ECAPTURE_GROUP"
	FOREIGN KEY("GROUP_ID")
	REFERENCES "ECAPTURE_GROUP"("GROUP_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_GROUP"
	ADD ( CONSTRAINT "FK_ECAPTURE_GROUP_PARENT"
	FOREIGN KEY("GROUP_PARENT_ID")
	REFERENCES "ECAPTURE_GROUP"("GROUP_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_LOG_MAIL"
	ADD ( CONSTRAINT "FK_ECAPTURE_LOG"
	FOREIGN KEY("LOG_ID")
	REFERENCES "ECAPTURE_LOG"("LOG_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_LOG_COMPONENT"
	ADD ( CONSTRAINT "FK_ECAPTURE_LOG_COMPONENT"
	FOREIGN KEY("LOG_ID")
	REFERENCES "ECAPTURE_LOG"("LOG_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_AUTHORITY_PERMISSIONS"
	ADD ( CONSTRAINT "FK_ECAPTURE_PERMISSION"
	FOREIGN KEY("PERMISSION_ID")
	REFERENCES "ECAPTURE_PERMISSION"("PERMISSION_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_PERMISSION"
	ADD ( CONSTRAINT "FK_ECAPTURE_PERMISSION_PARENT"
	FOREIGN KEY("PERMISSION_PARENT_ID")
	REFERENCES "ECAPTURE_PERMISSION"("PERMISSION_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_USER_AUTHORITY"
	ADD ( CONSTRAINT "FK_ECAPTURE_USER_AUTHORITY"
	FOREIGN KEY("AUTHORITY_ID")
	REFERENCES "ECAPTURE_AUTHORITY"("AUTHORITY_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_AUTHORITY_PERMISSIONS"
	ADD ( CONSTRAINT "FK_ECAPTURE_AUTHORITY_PERMISSIONS"
	FOREIGN KEY("AUTHORITY_ID")
	REFERENCES "ECAPTURE_AUTHORITY"("AUTHORITY_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_GROUP_AUTHORITY"
	ADD ( CONSTRAINT "FK_ECAPTURE_AUTHORITY"
	FOREIGN KEY("AUTHORITY_ID")
	REFERENCES "ECAPTURE_AUTHORITY"("AUTHORITY_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_LOG"
	ADD ( CONSTRAINT "FK_ECAPTURE_LOG_USER"
	FOREIGN KEY("USER_ID")
	REFERENCES "ECAPTURE_USER"("USER_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_USER_AUTHORITY"
	ADD ( CONSTRAINT "FK_ECAPTURE_USER"
	FOREIGN KEY("USER_ID")
	REFERENCES "ECAPTURE_USER"("USER_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
ALTER TABLE "ECAPTURE_GROUP_USER"
	ADD ( CONSTRAINT "FK_ECAPTURE_GROUP_USER_USER"
	FOREIGN KEY("USER_ID")
	REFERENCES "ECAPTURE_USER"("USER_ID")
	NOT DEFERRABLE  NOVALIDATE )
/
